build_report_jobs:
  ## infra.ci.jenkins.io jobs
  acceptance-tests-infra-ci:
    controller: infra.ci.jenkins.io
    job: acceptance-tests/acceptance-tests/check-agent-availability
    threshold_minutes: 1440
  kubernetes-management:
    controller: infra.ci.jenkins.io
    job: kubernetes-jobs/kubernetes-management/main
    threshold_minutes: 1440
  terraform-azure:
    controller: infra.ci.jenkins.io
    job: terraform-jobs/azure/main
    threshold_minutes: 1440
  terraform-azure-net:
    controller: infra.ci.jenkins.io
    job: terraform-jobs/azure-net/main
    threshold_minutes: 1440
  terraform-datadog:
    controller: infra.ci.jenkins.io
    job: terraform-jobs/datadog/main
    threshold_minutes: 1440
  terraform-digitalocean:
    controller: infra.ci.jenkins.io
    job: terraform-jobs/digitalocean/main
    threshold_minutes: 1440
  terraform-aws-sponsorship:
    controller: infra.ci.jenkins.io
    job: terraform-jobs/terraform-aws-sponsorship/main
    threshold_minutes: 1440
  docs-jenkins-io:
    controller: infra.ci.jenkins.io
    job: website-production-jobs/docs.jenkins.io/main
    threshold_minutes: 1440
  ## release.ci.jenkins.io jobs
  acceptance-tests-release-ci:
    controller: release.ci.jenkins.io
    job: infra-agents-health/master
    threshold_minutes: 1440  # 1 day (1 build)
  ## trusted.ci.jenkins.io jobs
  acceptance-tests-trusted-ci:
    controller: trusted.ci.jenkins.io
    job: acceptance-tests-check-agent-availability
    threshold_minutes: 1440
  core-taglibs-report-generator:
    controller: trusted.ci.jenkins.io
    job: core-taglibs-report-generator
    threshold_minutes: 10080  # 1 week (1 build)
  crawler:
    controller: trusted.ci.jenkins.io
    job: crawler
    threshold_minutes: 240  # 4 hours (1 build)
  javadoc:
    controller: trusted.ci.jenkins.io
    job: javadoc
    threshold_minutes: 10080  # 1 week (1 build)
  jenkins-io:
    controller: trusted.ci.jenkins.io
    job: jenkins.io
    threshold_minutes: 60  # (2 builds)
  repository-permissions-updater:
    controller: trusted.ci.jenkins.io
    job: repository-permissions-updater
    threshold_minutes: 360  # (2 builds)
  update-center:
    controller: trusted.ci.jenkins.io
    job: update_center
    threshold_minutes: 20  # (2 builds)
