FROM quay.io/roboll/helmfile:v0.78.0

LABEL \
  maintainer="https://github.com/olblak"

ADD https://github.com/mozilla/sops/releases/download/3.3.1/sops-3.3.1.linux /usr/local/bin/sops

RUN chmod +x /usr/local/bin/sops
