---
name: Update Artifact Caching Proxy AWS Settings

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  acpAwsSubnet:
    kind: json
    name: Retrieve the subnet ID for the ACP AWS LB from infra report
    spec:
      engine: dasel/v2
      file: https://reports.jenkins.io/jenkins-infra-data-reports/aws-sponsorship.json
      key: aws\.ci\.jenkins\.io.agents_kubernetes_clusters.cijenkinsio-agents-2.services.artifact-caching-proxy.subnet_id
  acpLbIp:
    kind: json
    name: Retrieve the LB private IP for the ACP AWS LB from infra report
    spec:
      engine: dasel/v2
      file: https://reports.jenkins.io/jenkins-infra-data-reports/aws-sponsorship.json
      key: aws\.ci\.jenkins\.io.agents_kubernetes_clusters.cijenkinsio-agents-2.services.artifact-caching-proxy.private_ip
  acpStorageClass:
    kind: json
    name: Retrieve the storage class to use for the ACP storage
    spec:
      engine: dasel/v2
      file: https://reports.jenkins.io/jenkins-infra-data-reports/aws-sponsorship.json
      key: aws\.ci\.jenkins\.io.agents_kubernetes_clusters.cijenkinsio-agents-2.services.artifact-caching-proxy.storage_class

targets:
  updateAcpLbIp:
    name: Update ACP LB IPv4
    sourceid: acpLbIp
    kind: yaml
    spec:
      file: config/cijioagents2/artifact-caching-proxy.yaml
      key: $.service.annotations.'service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses'
    scmid: default
  updateAcpLbSubnet:
    name: Update ACP LB Subnet
    sourceid: acpAwsSubnet
    kind: yaml
    spec:
      file: config/cijioagents2/artifact-caching-proxy.yaml
      key: $.service.annotations.'service.beta.kubernetes.io/aws-load-balancer-subnets'
    scmid: default
  updateAcpStorageClass:
    name: Update ACP Storage Class
    sourceid: acpStorageClass
    kind: yaml
    spec:
      file: config/cijioagents2/hub-mirror.yaml
      key: $.persistence.storageClass
    scmid: default

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Update configuration of the Artifact Caching Proxy for AWS
    spec:
      labels:
        - artifact-caching-proxy
        - cijioagents2
