name: Update list of IPs allowed to access LDAP

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  puppet.jenkins.io:
    kind: json
    name: Retrieve the puppet master outbound IPs
    spec:
      engine: dasel/v2
      file: https://reports.jenkins.io/jenkins-infra-data-reports/azure.json
      key: .puppet\.jenkins\.io.outbound_ips
    transformers:
      - addsuffix: '/32'

  publick8s-lb:
    name: Retrieve the publick8s outbound IPs
    kind: json
    spec:
      engine: dasel/v2
      file: https://reports.jenkins.io/jenkins-infra-data-reports/azure.json
      key: .publick8s.lb_outbound_ips.ipv4
    transformers:
      - trimprefix: '['
      - trimsuffix: ']'
      - replacer:
          from: ' '
          to: '/32,'
      - addsuffix: '/32'

  publick8s-pods:
    name: Retrieve the publick8s pod CNI CIDR
    kind: json
    spec:
      engine: dasel/v2
      file: https://reports.jenkins.io/jenkins-infra-data-reports/azure.json
      # Ipv4 is always the first element
      key: .publick8s.pod_cidrs.[0]

  # https://jfrog.com/knowledge-base/what-are-artifactory-cloud-nated-ips/
  jfrog:
    name: Retrieve the Jfrog (repo.jenkins-cio.org) outbound IPs
    kind: json
    spec:
      engine: dasel/v2
      file: https://my.jfrog.com/api/jmis/v1/ip-ranges
      key: all().filter(equal(cloud,aws)).filter(equal(region,us-east-1)).filter(equal(service,jfrog_cloud_cidr)).cidr.all().merge()
    # Change the json list to a comma-separated list into a single string
    transformers:
      - trimprefix: '['
      - trimsuffix: ']'
      - replacer:
          from: ' '
          to: ','

  aws-ci-jenkins-io:
    name: Retrieve the ci.jenkins.io outbound IPs from AWS
    kind: json
    spec:
      engine: dasel/v2
      file: https://reports.jenkins.io/jenkins-infra-data-reports/aws-sponsorship.json
      key: .aws\.ci\.jenkins\.io.service_ips.ipv4
    transformers:
      - addsuffix: "/32"

targets:
  puppet.jenkins.io:
    name: Update puppet.jenkins.io CIDR in the LDAP configuration
    kind: yaml
    sourceid: puppet.jenkins.io
    spec:
      file: config/publick8s/ldap-jenkins-io.yaml
      key: $.service.lbAllowSources.'puppet.jenkins.io'
    scmid: default

  publick8s-pods:
    name: Update publick8s pod CIDRs in the LDAP configuration
    kind: yaml
    sourceid: publick8s-pods
    spec:
      file: config/publick8s/ldap-jenkins-io.yaml
      key: $.service.lbAllowSources.publick8s-pods
    scmid: default

  publick8s-lb:
    name: Update publick8s outbound LB CIDRs in the LDAP configuration
    kind: yaml
    sourceid: publick8s-lb
    spec:
      file: config/publick8s/ldap-jenkins-io.yaml
      key: $.service.lbAllowSources.publick8s-out-lb
    scmid: default

  aws-ci-jenkins-io:
    name: Update aws.ci.jenkins.io CIDR in the LDAP configuration
    kind: yaml
    sourceid: aws-ci-jenkins-io
    spec:
      file: config/publick8s/ldap-jenkins-io.yaml
      key: $.service.lbAllowSources.'aws.ci.jenkins.io'
    scmid: default

  jfrog:
    name: Update JFrog CIDRs in the LDAP configuration
    kind: yaml
    sourceid: jfrog
    spec:
      file: config/publick8s/ldap-jenkins-io.yaml
      key: $.service.lbAllowSources.jfrog-artifactory
    scmid: default

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Update list of IPs allowed to access LDAP
    spec:
      labels:
        - enhancement
        - ldap
